# Top level design name
TARGET ?= devg_test_internal_pps_alsu_marble
FPGA_APPLICATION ?= devg_test_internal_pps_alsu
VIVADO_SYNTH_EXTRA_TCL += override_parameters.tcl

include ../devg_marble/Makefile
